---
- name: "harbor | main | Include generic variables."
  include_vars: "generic.yml"

- name: "harbor | main | Include OS-specific variables."
  include_vars: "{{ ansible_os_family }}.yml"

- name: "harbor | main | Installing pre dependencies of xorg-server"
  include: "{{ ansible_os_family }}.yml"

- name: "harbor | main | harbor"
  include: "harbor.yml"